<a href="https://colab.research.google.com/github/Soodeh84/DL_for_Computervision/blob/main/TensorFlow_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import numpy as np

# 1. Create 0D, 1D, 2D, 3D,...,nD tensors


In [ ]:
zeroD_tensor = tf.constant(7)
print(zeroD_tensor)

tf.Tensor(7, shape=(), dtype=int32)


In [ ]:
oneD_tensor = tf.constant([2,4,8])
print(oneD_tensor)
oneD_tensor_float = tf.constant([2,4,8, 5.9])
print(oneD_tensor_float)

tf.Tensor([2 4 8], shape=(3,), dtype=int32)
tf.Tensor([2.  4.  8.  5.9], shape=(4,), dtype=float32)


In [ ]:
twoD_tensor = tf.constant([
    [2, 3],
    [4, 5],
    [6, 7]
])
print(twoD_tensor)

tf.Tensor(
[[2 3]
 [4 5]
 [6 7]], shape=(3, 2), dtype=int32)


In [ ]:
threeD_tensor = tf.constant([
    [
        [2, 3, 1],
        [4, 5, 1],
        [6, 7, 1],
        [1, 1, 1]
    ],
    [
        [2, 3, 2],
        [4, 5, 2],
        [6, 7, 2],
        [2, 2, 2]
    ],
    [
        [2, 3, 3],
        [4, 5, 3],
        [6, 7, 3],
        [3, 3, 3]
    ],
    [
        [2, 3, 4],
        [4, 5, 4],
        [6, 7, 4],
        [4, 4, 4]
    ],
     [
        [2, 3, 5],
        [4, 5, 5],
        [6, 7, 5],
        [5, 5, 5]
    ]
])
print(threeD_tensor)

tf.Tensor(
[[[2 3 1]
  [4 5 1]
  [6 7 1]
  [1 1 1]]

 [[2 3 2]
  [4 5 2]
  [6 7 2]
  [2 2 2]]

 [[2 3 3]
  [4 5 3]
  [6 7 3]
  [3 3 3]]

 [[2 3 4]
  [4 5 4]
  [6 7 4]
  [4 4 4]]

 [[2 3 5]
  [4 5 5]
  [6 7 5]
  [5 5 5]]], shape=(5, 4, 3), dtype=int32)


In [ ]:
fourD_tensor = tf.constant([
    [[[1, 2, 1], [3, 4, 2]],
    [[5, 6, 3], [7, 8, 4]]],
    [[[1, 2, 5], [3, 4, 6]],
    [[5, 6, 7], [7, 8, 8]]],
    [[[1, 2, 9], [3, 4, 0]],
    [[5, 6, 1], [7, 8, 2]]]
    ])
print(fourD_tensor)

tf.Tensor(
[[[[1 2 1]
   [3 4 2]]

  [[5 6 3]
   [7 8 4]]]


 [[[1 2 5]
   [3 4 6]]

  [[5 6 7]
   [7 8 8]]]


 [[[1 2 9]
   [3 4 0]]

  [[5 6 1]
   [7 8 2]]]], shape=(3, 2, 2, 3), dtype=int32)


In [ ]:
print(fourD_tensor.ndim)

4


In [ ]:
print(fourD_tensor.shape)

(3, 2, 2, 3)


#2. Tensoe data types

In [ ]:
casting_tensor_type = tf.cast(oneD_tensor_float, dtype=tf.int16)
print(casting_tensor_type)

tf.Tensor([2 4 8 5], shape=(4,), dtype=int16)


In [ ]:
tensor_bool_type = tf.constant([False, True, True, False])
print(tensor_bool_type)

tf.Tensor([False  True  True False], shape=(4,), dtype=bool)


In [ ]:
casting_tensor_type = tf.cast(tensor_bool_type, dtype=tf.int16)
print(casting_tensor_type)

tf.Tensor([0 1 1 0], shape=(4,), dtype=int16)


In [ ]:
tensor_string = tf.constant(["Hello", "World", "!"])
print(tensor_string)

tf.Tensor([b'Hello' b'World' b'!'], shape=(3,), dtype=string)


#3. convert **numpy** to **tensor**

In [ ]:
oneD_np_array = np.array([0,1,4,8])
print(oneD_np_array)

[0 1 4 8]


In [ ]:
convert_np_to_tf = tf.convert_to_tensor(oneD_np_array)
print(convert_np_to_tf)

tf.Tensor([0 1 4 8], shape=(4,), dtype=int64)


*Note*: *check tensorFlow documentation for useful methods*
[TensorFlow methods](https://www.tensorflow.org/api_docs/python/tf/eye)

#4. tf.random: **Normal** & **Uniform** distributions

In [ ]:
random_tensor = tf.random.normal(
    [2,3], #shape
    mean=50.0,
    stddev=0.05,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor(
[[49.95727  49.944847 50.017918]
 [49.923416 50.01399  50.02085 ]], shape=(2, 3), dtype=float32)


In [ ]:
tensor_uniform = tf.random.uniform(
    [3, 2],
    minval=-20,
    maxval=10,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(tensor_uniform)

tf.Tensor(
[[  5.2065887 -18.306822 ]
 [ -9.039429  -11.463623 ]
 [  9.677984    8.409328 ]], shape=(3, 2), dtype=float32)


#5. Tensor indexing

In [ ]:
indexed_tensor = tf.constant([1,6, 40, 55, 3, 90, 2, 50])
print(indexed_tensor)
print(indexed_tensor[0:3]) #0 indexed element till 3rd element
print(indexed_tensor[1:3]) #1 indexed element till 3rd element
print(indexed_tensor[1:3+1]) #1 indexed element till 4th element
print(indexed_tensor[0:8:2]) #all elements with the steps of 2
print(indexed_tensor[3:]) #3 indexed element till the end
print(indexed_tensor[:3]) #0 indexed element till 3rd element
print(indexed_tensor[3:-1]) #3 indexed element till the max.element - 1


tf.Tensor([ 1  6 40 55  3 90  2 50], shape=(8,), dtype=int32)
tf.Tensor([ 1  6 40], shape=(3,), dtype=int32)
tf.Tensor([ 6 40], shape=(2,), dtype=int32)
tf.Tensor([ 6 40 55], shape=(3,), dtype=int32)
tf.Tensor([ 1 40  3  2], shape=(4,), dtype=int32)
tf.Tensor([55  3 90  2 50], shape=(5,), dtype=int32)
tf.Tensor([ 1  6 40], shape=(3,), dtype=int32)
tf.Tensor([55  3 90  2], shape=(4,), dtype=int32)


In [ ]:
twoD_indexing = tf.constant([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 0, 1, 2],
    [3, 4, 5, 6]
])
#print(twoD_indexing)
#print(twoD_indexing[0:2, 0:3]) #[rows , columns]
print(twoD_indexing[2:3, :]) #get the 3rd row which has index 2!
print(twoD_indexing[..., 1:2]) #get the 2nd column that has index 1!

tf.Tensor([[9 0 1 2]], shape=(1, 4), dtype=int32)
tf.Tensor(
[[2]
 [6]
 [0]
 [4]], shape=(4, 1), dtype=int32)


In [ ]:
threeD_indexing = tf.constant([
    [
       [1,2,3],
       [4,5,6]
    ],
    [
        [7,8,9],
        [0,1,2]
    ]
])
#print(threeD_indexing)
print(threeD_indexing[0 , : , 2:3]) #a: get from the 1st 2D matrix all elements in the last column -> 2D
#print(threeD_indexing[0 , : , 2:3].ndim)
#print(threeD_indexing[0 , : , 2:])  #b: same as a -> 2D
print(threeD_indexing[0 , : , -1])  #c: same result but in a row format -> 1D
#print(threeD_indexing[0 , : , -1].ndim)
#print(threeD_indexing[0 , ... , 2])   #d: same as c -> 1D

tf.Tensor(
[[3]
 [6]], shape=(2, 1), dtype=int32)
tf.Tensor([3 6], shape=(2,), dtype=int32)


#6. **Math** operations with Tensorflow
[tf.math](https://www.tensorflow.org/api_docs/python/tf/math)

In [ ]:
#math.argmax and math.argmin return the position index of the max and min elements
argMaxMin_v1 = tf.constant([2, 5, 10, 9, 11])
print(tf.math.argmax(argMaxMin_v1))
print(tf.math.argmin(argMaxMin_v1))

tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(0, shape=(), dtype=int64)


In [ ]:
print(twoD_indexing)
#make comparisons column by column and give the index of the max/min value!
#with default axis as 0
print(tf.math.argmax(twoD_indexing))
print(tf.math.argmin(twoD_indexing, 0))
#make comparisons row by row and give the index of the max/min value!
#with axis 1
print(tf.math.argmax(twoD_indexing, 1))
print(tf.math.argmin(twoD_indexing, 1))

tf.Tensor(
[[1 2 3 4]
 [5 6 7 8]
 [9 0 1 2]
 [3 4 5 6]], shape=(4, 4), dtype=int32)
tf.Tensor([2 1 1 1], shape=(4,), dtype=int64)
tf.Tensor([0 2 2 2], shape=(4,), dtype=int64)
tf.Tensor([3 3 0 3], shape=(4,), dtype=int64)
tf.Tensor([0 0 1 0], shape=(4,), dtype=int64)


#7. Linear Algebra operations
[tf.linalg](https://www.tensorflow.org/api_docs/python/tf/linalg)

In [ ]:
#matrix multiplications : tf.linalg.matmul
#note: for matrix multiplication number of coulumns of the first operand must
#be equal to the number of rows of the second operand
v1 = tf.constant([
    [1, 2, 3],
    [4, 5, 6],
    [1, 1, 0]
])
v2 = tf.constant([
    [9, 0, 1],
    [2, 3, 2],
    [1, 4, 3]
])
tf.linalg.matmul(
    v1,
    v2,
    transpose_a=False,
    transpose_b=False,
    adjoint_a=False,
    adjoint_b=False,
    a_is_sparse=False,
    b_is_sparse=False,
    output_type=None,
    name=None
)


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[16, 18, 14],
       [52, 39, 32],
       [11,  3,  3]], dtype=int32)>

In [ ]:
# v1 @ v2 -> matrix multiplication, while v1 * v2 is elemntwise multiplication
print(v1 @ v2 )
print(v1 * v2 )

tf.Tensor(
[[16 18 14]
 [52 39 32]
 [11  3  3]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[ 9  0  3]
 [ 8 15 12]
 [ 1  4  0]], shape=(3, 3), dtype=int32)


In [ ]:
#matrix transpose
tf.transpose(v1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 4, 1],
       [2, 5, 1],
       [3, 6, 0]], dtype=int32)>

In [ ]:
#einsum method ex1
print("v1: \n")
print(v1.numpy())
print("\n")
print("Einsum transpose v1 =: \n")
print(np.einsum('ij -> j', v1))

v1: 

[[1 2 3]
 [4 5 6]
 [1 1 0]]


Einsum transpose v1 =: 

[6 8 9]


In [ ]:
#einsum method ex2
a = np.array([
    [[2, 6, 5, 2],
     [2, -2, 2, 3],
     [1, 5, 4, 0]],
    [[1, 3, 1, 22],
     [0, 2, 2, 0],
     [1, 5, 4, 1]]
])
b = np.array([
    [[2, 9, 0, 3, 0],
     [3, 6, 8, -2, 2],
     [1, 3, 5, 0, 1],
     [3, 0, 2, 0, 5]],
    [[1, 0, 0, 3, 0],
     [3, 0, 4, -2, 2],
     [1, 0, 2, 0, 0],
     [3, 0, 1, 1, 0]]
])
print(a.shape, b.shape)
print("Results after batch multiplication (a*b): \n")
print(np.matmul(a,b), "\n")

print("Results using Einsum (bij,bjk -> bik): \n")
print(np.einsum('bij,bjk -> bik', a,b))

(2, 3, 4) (2, 4, 5)
Results after batch multiplication (a*b): 

[[[33 69 77 -6 27]
  [ 9 12  0 10 13]
  [21 51 60 -7 14]]

 [[77  0 36 19  6]
  [ 8  0 12 -4  4]
  [23  0 29 -6 10]]] 

Results using Einsum (bij,bjk -> bik): 

[[[33 69 77 -6 27]
  [ 9 12  0 10 13]
  [21 51 60 -7 14]]

 [[77  0 36 19  6]
  [ 8  0 12 -4  4]
  [23  0 29 -6 10]]]


In [ ]:
#einsum to sum up elements of a 3d tensor
print("Sum a => \n")
print(np.sum(a), "\n")

print("sum a using einsum => \n")
print(np.einsum('bij -> ', a)) #sum of all elemnt
print(np.einsum('bij -> bj', a)) #sum up column by column for each batch seperately

Sum a => 

72 

sum a using einsum => 

72
[[ 5  9 11  5]
 [ 2 10  7 23]]


In [ ]:
#einsum will use the transpose whenever it is necessary
Q = np.random.randn(2, 4, 5)
K = np.random.randn(2, 3, 5) #the transpose of this is needed (32, 512, 128): bmk
np.einsum("bqm,bkm -> bqk", Q,K).shape

(2, 4, 3)

#8. Common tf **functions**

In [ ]:
#tf.expand_dims -> add extra dimension to the specified axis
#tf.squeeze -> reduce dimension of the specified axis
#the expanded dimension is always 1
#only the dimension that is 1 or the expnded dimension can be squeeze
#tf.reshape can do the same as squeeze and more

v3 = tf.constant([[[2, 4, 6, 7]]])
print(v3.shape)

In [ ]:
v3_expanded = tf.expand_dims(v3, axis = 0)
print(v3_expanded)
print(v3_expanded.shape)

In [ ]:
v3_squeezed = tf.squeeze(v3_expanded, axis = 0)
print(v3_squeezed.shape)
for i in range(2):
  v3_squeezed = tf.squeeze(v3_squeezed, axis = 0)

print(v3_squeezed)
print(v3_squeezed.shape)

In [ ]:
#tf.concat -> concatenate two tensors
#2d tensors
a1 = tf.constant([
    [1, 2, 3],
    [4, 5, 6]
])
a2 = tf.constant([
    [9, 0, 1],
    [2, 3, 2]
])
print(a1.shape)
print(a2.shape)

tf.concat([a1, a2], axis = 0) #0 -> cocatenate them vertically

In [ ]:
tf.concat([a1, a2], axis = 1) #1 -> cocatenate them horizontally

In [ ]:
#3d tensors
b1 = tf.constant([
    [[2, 6, 5, 2],
     [2, -2, 2, 3],
     [1, 5, 4, 0]]
])
b2 = tf.constant([
    [[1, 3, 1, 22],
     [0, 2, 2, 0],
     [1, 5, 4, 1]]

])
print(b1.shape)
print(b2.shape)
tf.concat([b1, b2], axis = 0) #resulted shape: 4,3,4
#tf.concat([b1, b2], axis = 1) #resulted shape: 2, 6, 4
#tf.concat([b1, b2], axis = 2) #resulted shape: 2,3, 8

In [ ]:
#tf.stack -> it creates new axis, the specified one
#the shape of this new axis depends on the number of tensors
#stacking two tensors gives the shape of two in the specified axis
#it returns a tensor with higher dimension: 3d-> 4D
tf.stack([b1, b2], axis = 0) #resulted shape: (2),1,3,4

In [ ]:
tf.stack([b1, b2], axis = 1) #resulted shape: 1,(2),3,4

In [ ]:
tf.stack([b1, b2], axis = 2) #resulted shape: 1,3,(2),4

In [ ]:
#print(b1)
#print(b2)
tf.stack([b1, b2], axis = 3) #resulted shape: 1,3,4,(2)

Note1: instead of concatenating along a new axis is better to use stack:

tf.concat([tf.expand_dims(t, axis) for t in tensors], axis) <=> tf.stack(tensors, axis=axis)

Note2: On CPU, if an out of bound index is found, an error is returned. On GPU, if an out of bound index is found, a 0 is stored in the corresponding output value.

In [ ]:
#this gives same result as -> tf.stack([b1,b2], axis=3)
tf.concat([tf.expand_dims(t, axis = 3) for t in [b1,b2]], axis = 3)

In [ ]:
# pads a tensor with:
# tf.pad(tensor, paddings, mode='CONSTANT', constant_values=0, name=None)
t = tf.constant([[1, 2, 3],
                 [4, 5, 6]])
#surrond your tensor with the given pad
paddings = tf.constant([[1, 1,], #1 row on top,one row below
                        [2, 2]]) #2 cols left, 2 cols on right
# 'constant_values' is 0.
#tf.pad(t, paddings, "CONSTANT")  # [[0, 0, 0, 0, 0, 0, 0],
                                 #  [0, 0, 1, 2, 3, 0, 0],
                                 #  [0, 0, 4, 5, 6, 0, 0],
                                 #  [0, 0, 0, 0, 0, 0, 0]]
tf.pad(t, paddings, "CONSTANT", constant_values= 8)

In [ ]:
#tf.gather vs normal indexing
params = tf.constant(['p0', 'p1', 'p2', 'p3', 'p4', 'p5'])
params[1:3+1].numpy()

In [ ]:
tf.gather(params, [1,2,3]).numpy()

In [ ]:
#or:
tf.gather(params, tf.range(1,4)).numpy()

In [ ]:
#with gather function you can get any element at any position that you want:
tf.gather(params, [0,5,3]).numpy() #[p0,p5, p3]

In [ ]:
params = tf.constant([[0, 1.0, 2.0],
                      [10.0, 11.0, 12.0],
                      [20.0, 21.0, 22.0],
                      [30.0, 31.0, 32.0]])
tf.gather(params, indices=[3,1], axis = 0).numpy()

In [ ]:
tf.gather(params, indices=[2,1], axis = 1)

In [ ]:
params = tf.constant([
                      [[0, 1.0, 2.0],
                      [10.0, 11.0, 12.0],
                      [20.0, 21.0, 22.0],
                      [30.0, 31.0, 32.0]],

                      [[0, 10.0, 5.0],
                      [14.0, 1.0, 6.0],
                      [0.0, 3.0, 90.0],
                      [3.0, 4.0, 82.0]]
                     ])
print(params.shape)
tf.gather(params, [2,0], axis = 1)

In [ ]:
#tf.gather_nd(params, indices, batch_dims=0, name=None)
indices1 = [[[1,0],
             [0, 1],
             [0, 0],
             [1,1]]]

params1 = [[['a', 'b'],
            ['c', 'd']],

           [['e', 'f'],
            ['g', 'h']]]

indices2 = [[[1, 0],
             [0, 1]],

            [[0, 0],
             [1, 1]]]

params2 = [[['a', 'b'],
            ['c', 'd']],

           [['e', 'f'],
            ['g', 'h']]]
print(tf.gather_nd(params1, indices1),"\n")
print(tf.gather_nd(params2, indices2))

#9. Ragged Tensors

[tf.ragged](https://www.tensorflow.org/api_docs/python/tf/ragged)

[RAGGED TENSORS](https://www.tensorflow.org/api_docs/python/tf/RaggedTensor)

In [ ]:
#used when we have non-rectangular tensors
nonRect_tensor = [[1, 2],
                  [3],
                  [4, 5, 6]]

ragged_tensor = tf.ragged.constant(nonRect_tensor)
print(ragged_tensor.shape)
print(ragged_tensor)

In [ ]:
# Aliases for True & False so data and mask line up.
T, F = (True, False)

tf.ragged.boolean_mask(  # Mask a 2D Tensor.
    data=[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    mask=[[T, F, T], [F, F, F], [T, F, F]]).to_list()

In [ ]:
tf.ragged.boolean_mask(  # Mask rows of a 2D RaggedTensor.
    tf.ragged.constant([[1, 2, 3], [4], [5, 6]]),
    tf.ragged.constant([True, False, True])).to_list()

#10. Sparse Tensors -> efficient method to use for data with many Zeros!
[tf.sparse](https://www.tensorflow.org/api_docs/python/tf/sparse)

In [ ]:
#tf.sparse.SparseTensor(indices, values, dense_shape)
Mysparse_tensor = tf.sparse.SparseTensor(
    indices=[[1,1],[3, 4]], values= [33, 88], dense_shape= [4, 5])
print(Mysparse_tensor)

In [ ]:
tf.sparse.to_dense(Mysparse_tensor)

#11. String Tensors
[tf.strings](https://www.tensorflow.org/api_docs/python/tf/strings)

In [ ]:
Mystring_tensor = tf.constant(["Hello", "World", "!"])
print(Mystring_tensor)

In [ ]:
#tf.strings.join(inputs, separator='', name=None)
tf.strings.join(Mystring_tensor, separator='_', name=None)

#12. Tensor Variables
[VARIABLE](https://www.tensorflow.org/api_docs/python/tf/Variable)

In [ ]:
#tf.Variable(
#    initial_value=None,
#   trainable=None,
#   validate_shape=True,
#   caching_device=None,
#   name=None,
#   variable_def=None,
#   dtype=None,
#   import_scope=None,
#   constraint=None,
#   synchronization=tf.VariableSynchronization.AUTO,
#   aggregation=tf.compat.v1.VariableAggregation.NONE,
#   shape=None,
#   experimental_enable_variable_lifting=True
#)

# variables can be trained if the trainable is set to true

In [ ]:
x = tf.constant([1, 2])
x_var = tf.Variable(x, name= 'var1')
print(x_var)

In [ ]:
#x_var.assign_sub([3, 6])
#x_var.assign_add([3, 6])

In [ ]:
#with tf.device('GPU:0'):
#  x_var1 = tf.Variable(0.2)
#print(x_var1)
#print(x_var1.device)